import { createSlice } from "@reduxjs/toolkit";
import { useSelector } from "react-redux";

const initialState = {
  currentuser: null,
  error: null,
  loading: null,
};
const userSlice = createSlice({
  name: "user",
  initialState,
  reducers: {
    signInStart: (state) => {
      state.loading = true;
    },
    signInSuccess: (state, action) => {
      state.currentuser = action.payload;
      state.loading = false;
      state.error = null;
    },
    signInFailure: (state, action) => {
      state.currentuser = null;
      state.error = action.payload;
      state.loading = false;
    },
  },
});
export const useUserSelector = () => {
  return useSelector((state) => state.user);
};
export const { signInStart, signInSuccess, signInFailure } = userSlice.actions;

export default userSlice.reducer;

/*
When you dispatch an action in your component using the action creator generated by createSlice,
 you're providing the payload directly:
dispatch(increment(5)); this mean:{ type: 'increment', payload: 5 } so 5 is the payload

 */
